#Encoding: UTF-8
################################################################################
# This file is part of smc-get.
# Copyright (C) 2010-2011 Entertaining Software, Inc.
# Copyright (C) 2011 Marvin Gülker
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
################################################################################
#
#This is the configuration file for smc-get.
---
#This is the directory where everything gets installed into.
#Set this to the installation directory of SMC, e.g.
#/usr/share/smc.
#data_directory: "/usr/share/smc"
data_directory: "testdir"
#This is the URL of the repository where packages are downloaded from.
repo_url: "https://github.com/Luiji/Secret-Maryo-Chronicles-Contributed-Levels/raw/master/"

#Following you may specify default options for commands. The main key is the
#name of the command, the nested key the option you want to
#set and the value is the option's value. Check the
#documentation for possible option values.
#This is EXPERIMENTAL.
#Example (force to always reinstall on "install"):
#
#install:
#  reinstall: true
